### ISSUE TITLE
cmake fails on "Clang libraries not found (set CLANG_ROOT)"

### ISSUE THREAD

**Issue by Abh15h3k** [jrprice/Oclgrind#186]
I have tried exporting CLANG_ROOT=/lib/clang/10.0.0 ( which contains the 'bin' 'include' and 'lib' forlders ). but cmake is always failing at "Clang libraries not found (set CLANG_ROOT)"
Attaching my CMakeOutput.log

[CMakeOutput.log](https://github.com/jrprice/Oclgrind/files/4676095/CMakeOutput.log)

**Comment by Abh15h3k** [comment]
while breaking my head on this. i remembered another package that wouldn't build after version 10 of all these tools (gcc llvm) came out.

so i downgraded to gcc9 llvm9 clang9. and it builds and installs. properly.

**Comment by Abh15h3k** [comment]
but now make test. everything fails

**Comment by alexfikl** [comment]
This should be fixed by the buildsystem changes in #185 (at least it is for me on Arch as well).

For the `CLANG_ROOT` error in particular, Arch just seems to have a single `libclang-cpp`, not all the individual libs that Oclgrind was looking for, so cmake wasn't finding it.

**Comment by mdigiorgio** [comment]
Same issue here with `make test` building with gcc7 llvm7 and clang7, I get 97/98 failures. Any updates?

**Comment by ululi1970** [comment]
Having this issue with Ubuntu 18.04, LLVM 11, Clang-13. Exporting CLANG_ROOT=/usr/lib/clang/13/ does not solve the problem
